CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  salt VARCHAR(255),
  sessionToken VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS logs (
  id SERIAL PRIMARY KEY,
  useraction VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  entry TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);